server:
  port: ${MEDIA_SERVICE_PORT:8085}

auth0:
  issuer-uri: ${AUTH0_ISSUER_URI}
  audience: ${AUTH0_AUDIENCE}
  media:
    upload-base-url: ${MEDIA_UPLOAD_BASE_URL:https://upload.example.com}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

