spring:
  datasource:
    url: ${MODERATION_DB_URL}
    username: ${MODERATION_DB_USER}
    password: ${MODERATION_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    locations: classpath:db/migration

server:
  port: ${SERVER_PORT:${MODERATION_SERVICE_PORT:8086}}

auth0:
  issuer-uri: ${AUTH0_ISSUER_URI}
  audience: ${AUTH0_AUDIENCE}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

brooks:
  web:
    origins: ${BROOKS_WEB_ORIGINS}


