server:
  port: ${NOTIFICATIONS_SERVICE_PORT}

auth0:
  issuer-uri: ${AUTH0_ISSUER_URI}
  audience: ${AUTH0_AUDIENCE}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

brooks:
  web:
    origins: ${BROOKS_WEB_ORIGINS}

